name: Scrape latest data

on:
  workflow_dispatch:
  schedule:
    - cron:  '10 1 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v3
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    - name: Install and run
      run: |-
        yarn install
        yarn start
        yarn tocsv officers ranks discipline documents awards trainings
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
